version: '3.8'
services: 
    web:
        build: .
        container_name: server-container
        depends_on: 
            - db
        networks:
            - backend
        ports:
            - "8080:8080"
    db:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: loghme
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - backend

volumes:
    db-data:

networks:
    backend:
